pipeline:
  build:
    image: python
    commands:
      - pip install -r requirements.txt
  publish:
    image: plugins/docker
    username: flowq
    password: gjgj123a 
    repo: flowq/bar
    tags:
      - latest


