kind: pipeline
name: default

steps:
- name: web-flask
  image: python
  commands:
  - pip install -r requirements.txt

- name: publish
  image: plugins/docker
  settings:
      username:
          from_secret: username
      password: 
          from_secret: password
      auto_tag: true
      repo: flowq/bar
